### ISSUE TITLE
Features: Suggestions

### ISSUE THREAD

**Issue by KodingDev** [Sk1erLLC/Elementa#1]
Here's just a few suggestions that would make the GUI's we can create far more feature rich and appealing.

### Ideas
 * Add scrollable areas
 * Rounding shader
 * Outline constraint
 * Add text wrapping
 * Shadows

**Comment by FalseHonesty** [comment]
Text wrapping & rounding shaders are already on the feature list. What does an Outline Constraint entail?

**Comment by KodingKing1** [comment]
That would outline a component with a specified color, and could probably be added into the color constraints as an option instead.

**Comment by FalseHonesty** [comment]
You can't simply outline a gl draw, so adding it to the color constraint wouldn't be an option. It's possible we could add this as a feature and make it use a shader to outline, or we could just make it a component with a special scissor.

**Comment by KodingKing1** [comment]
Yep, that'd be fine. A shader would probably be the best way to do this. Also, is shadow support coming soon?

**Comment by FalseHonesty** [comment]
Doubtful, 2d drop shadows are not trivial to implement for arbitrary components. It'd be cool to support in the future, but it's not a given.

**Comment by FalseHonesty** [comment]
As an update, the "scrollable areas" feature is supported via the [ScrollComponent](https://github.com/Sk1erLLC/Elementa/blob/master/src/main/kotlin/club/sk1er/elementa/components/ScrollComponent.kt), and text wrapping via the [UIWrappedText](https://github.com/Sk1erLLC/Elementa/blob/master/src/main/kotlin/club/sk1er/elementa/components/UIWrappedText.kt). Unfortunately, the rest of these features are probably never going to happen due to my limited knowledge about GL shaders.

**Comment by FalseHonesty** [comment]
A basic rectangular outline can be achieved on any arbitrary component via the `OutlineEffect` added in 90ecbe805ca093cd481b2b917d206c89512eebc3.
