### ISSUE TITLE
Bug with at least 1.15+ Elementa

### ISSUE THREAD

**Issue by CyberDie22** [Sk1erLLC/Elementa#23]
**Describe the bug**
When loading the game, the game crashes, presumably because of the slick2d dependency (as I was told on the discord)

**To Reproduce**
1. Load the game
2. Crash

**Expected behavior**
I expected the game to not crash on startup

 - OS: Windows 10 2004

Crash Error:
https://pastebin.com/NpNSd7ud

**Comment by FalseHonesty** [comment]
Yeah, this issue is due to the Slick2D dependency (which uses LWJGL2) obviously being incompatible with 1.13+ LWJGL3. The only reason we have the Slick2D dependency is for custom font rendering, but I am currently working on replacing it with my own homegrown font renderer on the [msdf branch](/Sk1erLLC/Elementa/tree/msdf). That branch has made pretty solid progress, but we still have a decent bit of work left. I'll update this issue when that branch is merged. I don't want to promise anything, but expect this to be resolved in less than a week :)

**Comment by Sychic** [comment]
Should be fixed
